name: template-app
services:
  frontend:
    image: template-app/frontend
    build: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend
  backend:
    image: template-app/backend
    build: ./backend
    ports:
      - 5000:5000
    depends_on:
      cache:
        condition: service_started
      postgres:
        condition: service_healthy
  cache:
    image: bitnami/redis:7.0
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=mypassword
  postgres:
    image: postgres:16-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d app_db -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=app_db
